### ISSUE TITLE
Can't identify where web app is connecting to postgres

### ISSUE THREAD

**Issue by wrosko** [offerpool/offerpool#2]
Hey! I forked the repo and am in the process of modifying a few things with the intent to make a PR. 

I am meddling with the `.env` information and containers and whatnot. I am having a hard time identifying where the frontend/backend/app is connecting to the `postgres` server. I've tried searching for the env variables set as well as environment variable statements in the code but have not been able to identify where the client connection between the app and postgres is taking place. 

Apologies if it's a simple question, don't have much javascript experience, but looking forward to figuring out and seeing what you think of the PR!

**Comment by mikehw** [comment]
No worries!

`backend/utils/query-db.js` uses the npm package [pg](https://www.npmjs.com/package/pg) to expose a pooled connection to the Postgres database. pg uses Postgres' environment variable names for establishing the connection.

https://node-postgres.com/features/connecting
https://www.postgresql.org/docs/9.1/libpq-envars.html
