### ISSUE TITLE
repair   docker-compose Start failed

### ISSUE THREAD

**Issue by nangongchengfeng** [offerpool/offerpool#4]
![image](https://user-images.githubusercontent.com/46562911/153111245-b57bdcb0-484e-41a0-b975-4600e9e04689.png)

Hello, you need to add a horizontal bar here

docker-compose -p offerpool up -d

**Comment by mikehw** [comment]
`docker compose` was added in a more recent version of docker desktop for Mac and Windows and does not require the installation of `docker-compose`. Linux users will have to modify the step to `docker-compose` until docker's linux cli adds compose support.

https://docs.docker.com/compose/cli-command/
