### ISSUE TITLE
Unable to create an order

### ISSUE THREAD

**Issue by xmenccs** [offerpool/offerpool#8]
Hi, 

I'm using the API  to create an order: 

curl -s -X POST -H 'Content-Type: application/x-www-form-urlencoded' -d '{json}' -d {"offer":"offer1qqp83w76wzru6cmqvpsxygqqwc7hynr6hum6e0mnf72sn7uvvkpt68eyumkhelprk0adeg42nlelk2mpafrgx923m0l47ur2sxf7wreev6hj2fhdl6wjdq2m4vxdme0wwtxmef7gwc7faml8kvn2qyknwdrnsfhywt9dt8l50z6lh08nemh3tcv00h0gg4su45el3eth49eahleksmw4yhj0rrq0d09c04gla5l64cz7hjhn9w4jdz745axw59jfm80ulk0vuvs3r8vkcvn036k34kd7k80l9a6lmypfhr7ae3cmz7n2tkwy6kjtdj86d4vfm76ypswy2nzukastzdx6rfq56q4r4kgar4kgdp4kfdp4qghsn6wkrgq3w7ct3thp6jr277uhy7w43eyskf4yw5k9eeagehyrjs600nav9q44x7awlhyp9t9e67htw8vx8twzmwch0d3g4x285vg9lyjvd3ql3c87h506up009dqnt2yzy9ljcwu4wrfk0ppukhansfamdaj0769u6klc7fcdk20m34wh0mf552h3l2t7xphkyfx08mlkj2maal870lu3hrn0fnzhejeavs6tp7c2zrvskmyl7pvyngullxceecp78x4q82g2zs8ram7ynytnukuanwa6myu7l4w5n2esz0ez4gh3ttr827kw20cchuc9pcmlxw3l224q22dl7zuyhj7tdht704ulnywt2ul0qn6k8al8nm0zjdkk74h7hwctrk2hxksy2q9getl0lqnqgw8uamsxchnvu02nyu5f404lh5je5w6w79zydn0ykz0sl0kg2skg0f8zlu9s9cjzuhl9n86uah6jz6hhknhx28ahdpzmwfuge6tn36tmutf7ljh7jrlshh580elnq2ffd0f677fh659vmn2966n4l0w7t7lnhazzll5ewyutv4al7dcrmvysmlch5nmt39uen785jtl7rrc8takd54767hmuxkaknkkf7tghdm23ndh4hqzph7q9p2lylupy9mgj4pjugxx4njdtnqa37xrwaf4nww35ltc0t4cz60h3u4ktnf7ljmw9wt0m2vs2kre4pg2qu2c60ymtuexljp77rydew6a50k3rukwe7xmk5jajvjl7pw7jaylh6z5zpd674tv254a2arflx9637y89m88h9achm7tvjff0uvea3hl6dmh2l2ah8lh486wrnal46gfsvgfj9swk94gpel6h70hmvesll6dqjjvmgxgqe2shssqeglvat"} https://offerpool.io/api/v1/offers

{"success":false,"error_message":"invalid offer"}      <---- **but I always get this error, am I doing something wrong?**

**Comment by mikehw** [comment]
The `Content-Type` should be `application/json` and the body should be quoted. The below curl request was successful. 

>`curl -s -X POST -H 'Content-Type: application/json' -d '{"offer":"offer1qqp83w76wzru6cmqvpsxygqqwc7hynr6hum6e0mnf72sn7uvvkpt68eyumkhelprk0adeg42nlelk2mpafrgx923m0l47ur2sxf7wreev6hj2fhdl6wjdq2m4vxdme0wwtxmef7gwc7faml8kvn2qyknwdrnsfhywt9dt8l50z6lh08nemh3tcv00h0gg4su45el3eth49eahleksmw4yhj0rrq0d09c04gla5l64cz7hjhn9w4jdz745axw59jfm80ulk0vuvs3r8vkcvn036k34kd7k80l9a6lmypfhr7ae3cmz7n2tkwy6kjtdj86d4vfm76ypswy2nzukastzdx6rfq56q4r4kgar4kgdp4kfdp4qghsn6wkrgq3w7ct3thp6jr277uhy7w43eyskf4yw5k9eeagehyrjs600nav9q44x7awlhyp9t9e67htw8vx8twzmwch0d3g4x285vg9lyjvd3ql3c87h506up009dqnt2yzy9ljcwu4wrfk0ppukhansfamdaj0769u6klc7fcdk20m34wh0mf552h3l2t7xphkyfx08mlkj2maal870lu3hrn0fnzhejeavs6tp7c2zrvskmyl7pvyngullxceecp78x4q82g2zs8ram7ynytnukuanwa6myu7l4w5n2esz0ez4gh3ttr827kw20cchuc9pcmlxw3l224q22dl7zuyhj7tdht704ulnywt2ul0qn6k8al8nm0zjdkk74h7hwctrk2hxksy2q9getl0lqnqgw8uamsxchnvu02nyu5f404lh5je5w6w79zydn0ykz0sl0kg2skg0f8zlu9s9cjzuhl9n86uah6jz6hhknhx28ahdpzmwfuge6tn36tmutf7ljh7jrlshh580elnq2ffd0f677fh659vmn2966n4l0w7t7lnhazzll5ewyutv4al7dcrmvysmlch5nmt39uen785jtl7rrc8takd54767hmuxkaknkkf7tghdm23ndh4hqzph7q9p2lylupy9mgj4pjugxx4njdtnqa37xrwaf4nww35ltc0t4cz60h3u4ktnf7ljmw9wt0m2vs2kre4pg2qu2c60ymtuexljp77rydew6a50k3rukwe7xmk5jajvjl7pw7jaylh6z5zpd674tv254a2arflx9637y89m88h9achm7tvjff0uvea3hl6dmh2l2ah8lh486wrnal46gfsvgfj9swk94gpel6h70hmvesll6dqjjvmgxgqe2shssqeglvat"}' https://offerpool.io/api/v1/offers`
